<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.bahmni.module</groupId>
		<artifactId>fhir2Extension</artifactId>
		<version>2.0.0-c2c-496</version>
	</parent>

	<artifactId>fhir2Extension-omod</artifactId>
	<packaging>jar</packaging>
	<name>FHIR2 module extensions OMOD</name>
	<description>OpenMRS module project for FHIR2 Extensions</description>

	<dependencies>
        <dependency>
            <groupId>org.bahmni.module</groupId>
            <artifactId>fhir2Extension-api</artifactId>
            <version>${project.parent.version}</version>
        </dependency>
		<dependency>
			<groupId>org.openmrs.module</groupId>
			<artifactId>fhir2-api</artifactId>
		</dependency>
		<dependency>
			<groupId>org.openmrs.module</groupId>
			<artifactId>webservices.rest-omod-common</artifactId>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
		</dependency>
		<dependency>
			<groupId>org.openmrs.web</groupId>
			<artifactId>openmrs-web</artifactId>
			<version>${openmrsPlatformVersion}</version>
			<scope>provided</scope>
			<exclusions>
				<exclusion>
					<groupId>javax.servlet</groupId>
					<artifactId>jstl</artifactId>
				</exclusion>
				<exclusion>
					<groupId>javax.servlet</groupId>
					<artifactId>jsp-api</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<!--        Test Dependencies       -->
		<dependency>
			<groupId>org.openmrs.web</groupId>
			<artifactId>openmrs-web</artifactId>
			<version>${openmrsPlatformVersion}</version>
			<scope>provided</scope>
			<classifier>tests</classifier>
		</dependency>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-core</artifactId>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.hamcrest</groupId>
					<artifactId>hamcrest-core</artifactId>
				</exclusion>
			</exclusions>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<finalName>${project.parent.artifactId}-${project.parent.version}</finalName>
		<plugins>
			<plugin>
				<groupId>org.openmrs.maven.plugins</groupId>
				<artifactId>maven-openmrs-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
